/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CryptoPriceGuessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPredictionEvent"
      | "decryptionCallback"
      | "endPredictionEvent"
      | "finalizePredictionEvent"
      | "getDecryptedAveragePrice"
      | "getEncryptedPriceSum"
      | "getEventCount"
      | "getPredictionEvent"
      | "getUserEncryptedPrediction"
      | "hasUserPredicted"
      | "predictionEvents"
      | "protocolId"
      | "setActualPrice"
      | "submitPrediction"
      | "userPredictions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActualPriceSet"
      | "FinalizeRequested"
      | "PredictionEventCreated"
      | "PredictionEventEnded"
      | "PredictionEventFinalized"
      | "PredictionSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPredictionEvent",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "endPredictionEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePredictionEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedAveragePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedPriceSum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEncryptedPrediction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserPredicted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictionEvents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setActualPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPrediction",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userPredictions",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPredictionEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endPredictionEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePredictionEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedAveragePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedPriceSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEncryptedPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserPredicted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictionEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setActualPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userPredictions",
    data: BytesLike
  ): Result;
}

export namespace ActualPriceSetEvent {
  export type InputTuple = [eventId: BigNumberish, actualPrice: BigNumberish];
  export type OutputTuple = [eventId: bigint, actualPrice: bigint];
  export interface OutputObject {
    eventId: bigint;
    actualPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FinalizeRequestedEvent {
  export type InputTuple = [eventId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [eventId: bigint, requestId: bigint];
  export interface OutputObject {
    eventId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionEventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    title: string,
    tokenType: BigNumberish,
    admin: AddressLike
  ];
  export type OutputTuple = [
    eventId: bigint,
    title: string,
    tokenType: bigint,
    admin: string
  ];
  export interface OutputObject {
    eventId: bigint;
    title: string;
    tokenType: bigint;
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionEventEndedEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionEventFinalizedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    decryptedAveragePrice: BigNumberish,
    actualPrice: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    decryptedAveragePrice: bigint,
    actualPrice: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    decryptedAveragePrice: bigint;
    actualPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionSubmittedEvent {
  export type InputTuple = [eventId: BigNumberish, user: AddressLike];
  export type OutputTuple = [eventId: bigint, user: string];
  export interface OutputObject {
    eventId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CryptoPriceGuess extends BaseContract {
  connect(runner?: ContractRunner | null): CryptoPriceGuess;
  waitForDeployment(): Promise<this>;

  interface: CryptoPriceGuessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPredictionEvent: TypedContractMethod<
    [
      _title: string,
      _tokenType: BigNumberish,
      _targetDate: BigNumberish,
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  endPredictionEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizePredictionEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDecryptedAveragePrice: TypedContractMethod<
    [_eventId: BigNumberish],
    [bigint],
    "view"
  >;

  getEncryptedPriceSum: TypedContractMethod<
    [_eventId: BigNumberish],
    [string],
    "view"
  >;

  getEventCount: TypedContractMethod<[], [bigint], "view">;

  getPredictionEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        title: string;
        tokenType: bigint;
        targetDate: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalPredictions: bigint;
        actualPrice: bigint;
        decryptedAveragePrice: bigint;
      }
    ],
    "view"
  >;

  getUserEncryptedPrediction: TypedContractMethod<
    [_eventId: BigNumberish, _user: AddressLike],
    [string],
    "view"
  >;

  hasUserPredicted: TypedContractMethod<
    [_eventId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  predictionEvents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        title: string;
        tokenType: bigint;
        targetDate: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalPredictions: bigint;
        actualPrice: bigint;
        encryptedPriceSum: string;
        decryptedAveragePrice: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setActualPrice: TypedContractMethod<
    [_eventId: BigNumberish, _actualPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitPrediction: TypedContractMethod<
    [_eventId: BigNumberish, _encryptedPrice: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  userPredictions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedPrice: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPredictionEvent"
  ): TypedContractMethod<
    [
      _title: string,
      _tokenType: BigNumberish,
      _targetDate: BigNumberish,
      _durationInHours: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endPredictionEvent"
  ): TypedContractMethod<[_eventId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizePredictionEvent"
  ): TypedContractMethod<[_eventId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDecryptedAveragePrice"
  ): TypedContractMethod<[_eventId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedPriceSum"
  ): TypedContractMethod<[_eventId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEventCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPredictionEvent"
  ): TypedContractMethod<
    [_eventId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        title: string;
        tokenType: bigint;
        targetDate: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalPredictions: bigint;
        actualPrice: bigint;
        decryptedAveragePrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEncryptedPrediction"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _user: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserPredicted"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictionEvents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        title: string;
        tokenType: bigint;
        targetDate: bigint;
        endTime: bigint;
        isActive: boolean;
        isFinalized: boolean;
        admin: string;
        totalPredictions: bigint;
        actualPrice: bigint;
        encryptedPriceSum: string;
        decryptedAveragePrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setActualPrice"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _actualPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPrediction"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _encryptedPrice: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userPredictions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, boolean] & {
        encryptedPrice: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ActualPriceSet"
  ): TypedContractEvent<
    ActualPriceSetEvent.InputTuple,
    ActualPriceSetEvent.OutputTuple,
    ActualPriceSetEvent.OutputObject
  >;
  getEvent(
    key: "FinalizeRequested"
  ): TypedContractEvent<
    FinalizeRequestedEvent.InputTuple,
    FinalizeRequestedEvent.OutputTuple,
    FinalizeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionEventCreated"
  ): TypedContractEvent<
    PredictionEventCreatedEvent.InputTuple,
    PredictionEventCreatedEvent.OutputTuple,
    PredictionEventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionEventEnded"
  ): TypedContractEvent<
    PredictionEventEndedEvent.InputTuple,
    PredictionEventEndedEvent.OutputTuple,
    PredictionEventEndedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionEventFinalized"
  ): TypedContractEvent<
    PredictionEventFinalizedEvent.InputTuple,
    PredictionEventFinalizedEvent.OutputTuple,
    PredictionEventFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionSubmitted"
  ): TypedContractEvent<
    PredictionSubmittedEvent.InputTuple,
    PredictionSubmittedEvent.OutputTuple,
    PredictionSubmittedEvent.OutputObject
  >;

  filters: {
    "ActualPriceSet(uint256,uint256)": TypedContractEvent<
      ActualPriceSetEvent.InputTuple,
      ActualPriceSetEvent.OutputTuple,
      ActualPriceSetEvent.OutputObject
    >;
    ActualPriceSet: TypedContractEvent<
      ActualPriceSetEvent.InputTuple,
      ActualPriceSetEvent.OutputTuple,
      ActualPriceSetEvent.OutputObject
    >;

    "FinalizeRequested(uint256,uint256)": TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;
    FinalizeRequested: TypedContractEvent<
      FinalizeRequestedEvent.InputTuple,
      FinalizeRequestedEvent.OutputTuple,
      FinalizeRequestedEvent.OutputObject
    >;

    "PredictionEventCreated(uint256,string,uint8,address)": TypedContractEvent<
      PredictionEventCreatedEvent.InputTuple,
      PredictionEventCreatedEvent.OutputTuple,
      PredictionEventCreatedEvent.OutputObject
    >;
    PredictionEventCreated: TypedContractEvent<
      PredictionEventCreatedEvent.InputTuple,
      PredictionEventCreatedEvent.OutputTuple,
      PredictionEventCreatedEvent.OutputObject
    >;

    "PredictionEventEnded(uint256)": TypedContractEvent<
      PredictionEventEndedEvent.InputTuple,
      PredictionEventEndedEvent.OutputTuple,
      PredictionEventEndedEvent.OutputObject
    >;
    PredictionEventEnded: TypedContractEvent<
      PredictionEventEndedEvent.InputTuple,
      PredictionEventEndedEvent.OutputTuple,
      PredictionEventEndedEvent.OutputObject
    >;

    "PredictionEventFinalized(uint256,uint32,uint256)": TypedContractEvent<
      PredictionEventFinalizedEvent.InputTuple,
      PredictionEventFinalizedEvent.OutputTuple,
      PredictionEventFinalizedEvent.OutputObject
    >;
    PredictionEventFinalized: TypedContractEvent<
      PredictionEventFinalizedEvent.InputTuple,
      PredictionEventFinalizedEvent.OutputTuple,
      PredictionEventFinalizedEvent.OutputObject
    >;

    "PredictionSubmitted(uint256,address)": TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
    PredictionSubmitted: TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
  };
}
